### PR TITLE
proxy: Allow bearer auth request to pass through proxy. Closes #287

### LINKED ISSUE #287: Bearer Token Authorization?
Does the reverse proxy prevent a parse through of the Authorization header and is there any way I can prevent it?

Used up for a small project for work to get a quick result and just stuck on this one piece.

I get a 502 on anything that is not a valid Basic Authorization header, trying to pass through a Bearer token.

### PR DESCRIPTION
**Pull request by skabbes**
Fixes https://github.com/apex/up/issues/287

The up proxy is specifically trying to parse all auth types as Basic auth, however there are other kinds of authentication that we need to allow to passthrough untouched.

This PR does 2 specific things:
1. Small refactoring, code changes and tests to allow Bearer auth
1. Explicitly using the io.Reader from the `bytes` package for binary requests

Admittedly, 2 wasn't really necessary - so feel free to not accept it, cherry-pick it away, commandeer this PR, etc.

My experience with up was that I got it up and running very fast (usually testing on non-authenticated endpoints), however got quickly discouraged when cloudfront was returning `502 "Error from cloudfront"` on any _real_ requests.

### CODE REVIEW

**Comment by tj** [comment]
ahh I forgot I had that `URL.User` stuff in there, I'll double check but I think it should be safe to completely remove

**Comment by skabbes** [comment]
Ya, I thought that might be a better solution, but without knowing why it was all there I was scared to remove.  If you double check, I can close this and open a new one that just remove the auth parsing in general.

**Comment by tj** [comment]
haha yeah that's fair, I'll get the test coverage up there too. Definitely proxies fine, the only lame thing is that API Gateway remaps www-authenticate:

```
x-amzn-remapped-www-authenticate:Basic realm="Test"
```

but for your case it should still be ok, no idea why they're doing that, really want people to use "custom authorizers" I guess

**Comment by skabbes** [comment]
Ya amazon has to get that lock-in somehow.

Cool, I just saw the commit on master - that feels a lot better, awesome.

**Pull request closed without merging**
