### PR TITLE
test: add test cases for platform cost

### PR DESCRIPTION
**Pull request by jalateras**
Adding test cases to the `cost` package

### CODE REVIEW

**Comment by jalateras** [comment]
This is `wip`  and will add more tests once i get feedback on the style.

**Comment by jalateras** [comment]
Changed the implementation of `Total` so that you specify the number of requests and the length of invocation per request. I think that probably makes more sense.

I haven't added test cases to cover boundary conditions such as < 0 etc didn't think that was required

**Comment by tj** [comment]
cool thanks! Yeah I wouldn't worry about < 0 either. Looks like we're not even using `Total` :D hahah, we could just remove that for now

**Comment by stephenmathieson** [comment]
I just got my first Up-powered bill... $0.56. Not too bad, haha!!

**Comment by jalateras** [comment]
Personally, I would leave it because you reckon we would eventually use it but happy for you to make the call.

**Pull request merged**
