### PR TITLE
add support for substituting env vars from shell in environment config

### PR DESCRIPTION
**Pull request by selvakn**
No issue created for this feature. Hope it is ok.

PS: This solution can be an alternate for #366 for me.

### CODE REVIEW

**Comment by tj** [comment]
I'm not sure we'll need it TBH, because those environment variables are transmitted unencrypted it doesn't help much on the security side of things.

The Pro plan has (need to finish billing stuff) `up env ...` for encrypted secret CRUD which is more appropriate I think. I'm not against substitution for other reasons but I'm curious about the use-cases

**Comment by tj** [comment]
Actually, this might be nice for the `up env` case as well. Right now it's not mandatory to specify which env vars are required, but supporting `$FOO` would be a nice way to optionally specify that it is required.

**Comment by selvakn** [comment]
Use-case is to set secrets which are different for each stage. And these secrets (managed by CI) are going to be injected as ENV vars during build/deploy steps.

And Im waiting for the pro features, with which, it is safe (and encrypted), but want a workaround today! :) and hoping it would be out soon.

Im good with my fork for now. and will switch back when the feature is out. Thanks for the good work!

**Comment by tj** [comment]
oops forgot to re-open :D

**Comment by kevinsimper** [comment]
This would work great for me!

**Comment by nunofgs** [comment]
Just needed this feature. @tj any news on this?

**Comment by tj** [comment]
@nunofgs should be getting to these PRs pretty soon. I'm a little hesitant about this one, since it's much nicer to have the env vars team-wide, not just local, and unencrypted in transit. I think might encourage bad practices.

However I would like to have a way to list the env vars required so that an app cannot be deployed without them being defined first!

**Comment by kevinsimper** [comment]
@tj but maybe you don't want to buy more in to the AWS ecosystem :)

**Comment by tj** [comment]
That's the point of Up though haha, to abstract that away.

I'm going to close this one for now, since requiring the vars to be defined is a separate task. I think this will encourage poor practices. Thank you though!

**Pull request closed without merging**
