### PR TITLE
shim: refactor nodejs shim to work on node8 or node10

### PR DESCRIPTION
**Pull request by skabbes**
No breaking changes to any code, you can simply specify:

```
"lambda": {
  "runtime": "nodejs10.x"
}
```

to select the nodejs 10.x runtime on AWS.  The node 8 runtime will continue to work, as the shim is compatible with both versions of node.

I have run this against our company's internal website with no issue (node 8), and will run on node10 this afternoon to burn that in too.

### CODE REVIEW

**Comment by skabbes** [comment]
Over 1 week of testing "in production" on a node.js server running node10. And several "static" sites as well, no problem - all running smoothly.  

I used to embed node10 directly in the lambda package, and saved _so_ much extra space not having to do that anymore.  Now, I have so much more room for `left-pad` and similar node_modules!

**Comment by tj** [comment]
Whoop! I'll check this out again when I'm back from NYC next week!

**Comment by tj** [comment]
merged! thanks man!

**Comment by loganpowell** [comment]
Thank you @skabbes !

**Pull request closed without merging**
